server:
  address: localhost
  port: 8088
  servlet:
    context-path: /

spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/buysell
    username: postgres
    password: postgres
    initialize: true

  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none


  liquibase:
    enabled: true